[package]
name = "arduino-console"
version = "0.1.0"
edition = "2024"

[dependencies.avr-device]
version = "0.8.1"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
features = ["arduino-uno"]